on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - run: make release
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
